name: Deploy documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache .pyprojectx
        uses: actions/cache@v2
        env:
          cache-name: .pyprojectx
        with:
          path: .pyprojectx
          key: pyprojectx

      - name: Build docs
        run: python pw generate-docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: pyprojectx/pyprojectx.github.io
          branch: main
          folder: docs/site
